version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: codesanook-ef-note:latest
    volumes:
      - ./app:/app # ./app on local map to /app in the container
    ports:
      - "8000:8000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=codesanook-ef-note;Uid=sa;Pwd=#5SR^Yz4!3N4jRE@;"
    depends_on:
      - db
    networks:
      - compose_network
  db:
    image: mysql:5.7
    restart: always
    environment:
      # TODO move password to a secret file
      MYSQL_ROOT_PASSWORD: MySQL1234!
      # Set permission of this user in "set-database-permission.sql"
      MYSQL_USER: sa
      MYSQL_PASSWORD: "#5SR^Yz4!3N4jRE@"
      MYSQL_DATABASE: codesanook-ef-note
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      retries: 10
    volumes:
      # Use name volumes, managed by Docker for local development
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql

      # Map all files in init folder as initialize database files
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql

      # Use a custom MySQL configuration file
      - ./config:/etc/mysql/conf.d
    command:
      [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    networks:
      - compose_network

# https://docs.docker.com/compose/compose-file/compose-file-v3/#external-1
volumes:
  mysql-data:
  mysql-logs:

# https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference
# Full document https://docs.docker.com/compose/networking/
networks:
  compose_network:
